// Code generated by protoc-gen-go. DO NOT EDIT.
// source: minion/pb/pb.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	minion/pb/pb.proto

It has these top-level messages:
	MinionConfig
	Reply
	Request
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MinionConfig_Role int32

const (
	MinionConfig_NONE   MinionConfig_Role = 0
	MinionConfig_WORKER MinionConfig_Role = 1
	MinionConfig_MASTER MinionConfig_Role = 2
)

var MinionConfig_Role_name = map[int32]string{
	0: "NONE",
	1: "WORKER",
	2: "MASTER",
}
var MinionConfig_Role_value = map[string]int32{
	"NONE":   0,
	"WORKER": 1,
	"MASTER": 2,
}

func (x MinionConfig_Role) String() string {
	return proto.EnumName(MinionConfig_Role_name, int32(x))
}
func (MinionConfig_Role) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type MinionConfig struct {
	ID             string            `protobuf:"bytes,1,opt,name=ID" json:"ID,omitempty"`
	Role           MinionConfig_Role `protobuf:"varint,2,opt,name=role,enum=MinionConfig_Role" json:"role,omitempty"`
	PrivateIP      string            `protobuf:"bytes,3,opt,name=PrivateIP" json:"PrivateIP,omitempty"`
	PublicIP       string            `protobuf:"bytes,4,opt,name=PublicIP" json:"PublicIP,omitempty"`
	Blueprint      string            `protobuf:"bytes,5,opt,name=Blueprint" json:"Blueprint,omitempty"`
	Provider       string            `protobuf:"bytes,6,opt,name=Provider" json:"Provider,omitempty"`
	Size           string            `protobuf:"bytes,7,opt,name=Size" json:"Size,omitempty"`
	Region         string            `protobuf:"bytes,8,opt,name=Region" json:"Region,omitempty"`
	FloatingIP     string            `protobuf:"bytes,9,opt,name=FloatingIP" json:"FloatingIP,omitempty"`
	EtcdMembers    []string          `protobuf:"bytes,10,rep,name=EtcdMembers" json:"EtcdMembers,omitempty"`
	AuthorizedKeys []string          `protobuf:"bytes,11,rep,name=AuthorizedKeys" json:"AuthorizedKeys,omitempty"`
}

func (m *MinionConfig) Reset()                    { *m = MinionConfig{} }
func (m *MinionConfig) String() string            { return proto.CompactTextString(m) }
func (*MinionConfig) ProtoMessage()               {}
func (*MinionConfig) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *MinionConfig) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *MinionConfig) GetRole() MinionConfig_Role {
	if m != nil {
		return m.Role
	}
	return MinionConfig_NONE
}

func (m *MinionConfig) GetPrivateIP() string {
	if m != nil {
		return m.PrivateIP
	}
	return ""
}

func (m *MinionConfig) GetPublicIP() string {
	if m != nil {
		return m.PublicIP
	}
	return ""
}

func (m *MinionConfig) GetBlueprint() string {
	if m != nil {
		return m.Blueprint
	}
	return ""
}

func (m *MinionConfig) GetProvider() string {
	if m != nil {
		return m.Provider
	}
	return ""
}

func (m *MinionConfig) GetSize() string {
	if m != nil {
		return m.Size
	}
	return ""
}

func (m *MinionConfig) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

func (m *MinionConfig) GetFloatingIP() string {
	if m != nil {
		return m.FloatingIP
	}
	return ""
}

func (m *MinionConfig) GetEtcdMembers() []string {
	if m != nil {
		return m.EtcdMembers
	}
	return nil
}

func (m *MinionConfig) GetAuthorizedKeys() []string {
	if m != nil {
		return m.AuthorizedKeys
	}
	return nil
}

type Reply struct {
}

func (m *Reply) Reset()                    { *m = Reply{} }
func (m *Reply) String() string            { return proto.CompactTextString(m) }
func (*Reply) ProtoMessage()               {}
func (*Reply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type Request struct {
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func init() {
	proto.RegisterType((*MinionConfig)(nil), "MinionConfig")
	proto.RegisterType((*Reply)(nil), "Reply")
	proto.RegisterType((*Request)(nil), "Request")
	proto.RegisterEnum("MinionConfig_Role", MinionConfig_Role_name, MinionConfig_Role_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Minion service

type MinionClient interface {
	SetMinionConfig(ctx context.Context, in *MinionConfig, opts ...grpc.CallOption) (*Reply, error)
	GetMinionConfig(ctx context.Context, in *Request, opts ...grpc.CallOption) (*MinionConfig, error)
}

type minionClient struct {
	cc *grpc.ClientConn
}

func NewMinionClient(cc *grpc.ClientConn) MinionClient {
	return &minionClient{cc}
}

func (c *minionClient) SetMinionConfig(ctx context.Context, in *MinionConfig, opts ...grpc.CallOption) (*Reply, error) {
	out := new(Reply)
	err := grpc.Invoke(ctx, "/Minion/SetMinionConfig", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *minionClient) GetMinionConfig(ctx context.Context, in *Request, opts ...grpc.CallOption) (*MinionConfig, error) {
	out := new(MinionConfig)
	err := grpc.Invoke(ctx, "/Minion/GetMinionConfig", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Minion service

type MinionServer interface {
	SetMinionConfig(context.Context, *MinionConfig) (*Reply, error)
	GetMinionConfig(context.Context, *Request) (*MinionConfig, error)
}

func RegisterMinionServer(s *grpc.Server, srv MinionServer) {
	s.RegisterService(&_Minion_serviceDesc, srv)
}

func _Minion_SetMinionConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MinionConfig)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinionServer).SetMinionConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Minion/SetMinionConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinionServer).SetMinionConfig(ctx, req.(*MinionConfig))
	}
	return interceptor(ctx, in, info, handler)
}

func _Minion_GetMinionConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinionServer).GetMinionConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Minion/GetMinionConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinionServer).GetMinionConfig(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _Minion_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Minion",
	HandlerType: (*MinionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetMinionConfig",
			Handler:    _Minion_SetMinionConfig_Handler,
		},
		{
			MethodName: "GetMinionConfig",
			Handler:    _Minion_GetMinionConfig_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "minion/pb/pb.proto",
}

func init() { proto.RegisterFile("minion/pb/pb.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 343 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x91, 0x41, 0x6b, 0xe2, 0x40,
	0x14, 0xc7, 0x4d, 0x8c, 0x31, 0x79, 0xee, 0xaa, 0xbc, 0xc3, 0x32, 0xc8, 0xb2, 0x84, 0x1c, 0x24,
	0x2c, 0x4b, 0x04, 0xf7, 0x13, 0xd8, 0x9a, 0x96, 0x20, 0x6a, 0x18, 0x0b, 0x3d, 0x1b, 0x9d, 0xda,
	0x81, 0x98, 0x49, 0xc7, 0x89, 0xa0, 0x1f, 0xbd, 0xa7, 0xe2, 0x18, 0xac, 0x7a, 0x9b, 0xf7, 0x7b,
	0xff, 0xdf, 0x1c, 0xfe, 0x0f, 0x70, 0xcb, 0x73, 0x2e, 0xf2, 0x41, 0x91, 0x0e, 0x8a, 0x34, 0x2c,
	0xa4, 0x50, 0xc2, 0xff, 0x34, 0xe1, 0xc7, 0x54, 0xe3, 0x47, 0x91, 0xbf, 0xf1, 0x0d, 0xb6, 0xc1,
	0x8c, 0xc7, 0xc4, 0xf0, 0x8c, 0xc0, 0xa5, 0x66, 0x3c, 0xc6, 0x3e, 0x58, 0x52, 0x64, 0x8c, 0x98,
	0x9e, 0x11, 0xb4, 0x87, 0x18, 0x5e, 0x87, 0x43, 0x2a, 0x32, 0x46, 0xf5, 0x1e, 0x7f, 0x83, 0x9b,
	0x48, 0xbe, 0x5f, 0x2a, 0x16, 0x27, 0xa4, 0xae, 0xf5, 0x6f, 0x80, 0x3d, 0x70, 0x92, 0x32, 0xcd,
	0xf8, 0x2a, 0x4e, 0x88, 0xa5, 0x97, 0x97, 0xf9, 0x64, 0x3e, 0x64, 0x25, 0x2b, 0x24, 0xcf, 0x15,
	0x69, 0x9c, 0xcd, 0x0b, 0xd0, 0xa6, 0x14, 0x7b, 0xbe, 0x66, 0x92, 0xd8, 0x95, 0x59, 0xcd, 0x88,
	0x60, 0x2d, 0xf8, 0x91, 0x91, 0xa6, 0xe6, 0xfa, 0x8d, 0xbf, 0xc0, 0xa6, 0x6c, 0xc3, 0x45, 0x4e,
	0x1c, 0x4d, 0xab, 0x09, 0xff, 0x00, 0x3c, 0x65, 0x62, 0xa9, 0x78, 0xbe, 0x89, 0x13, 0xe2, 0xea,
	0xdd, 0x15, 0x41, 0x0f, 0x5a, 0x91, 0x5a, 0xad, 0xa7, 0x6c, 0x9b, 0x32, 0xb9, 0x23, 0xe0, 0xd5,
	0x03, 0x97, 0x5e, 0x23, 0xec, 0x43, 0x7b, 0x54, 0xaa, 0x77, 0x21, 0xf9, 0x91, 0xad, 0x27, 0xec,
	0xb0, 0x23, 0x2d, 0x1d, 0xba, 0xa3, 0x7e, 0x00, 0xd6, 0xa9, 0x17, 0x74, 0xc0, 0x9a, 0xcd, 0x67,
	0x51, 0xb7, 0x86, 0x00, 0xf6, 0xeb, 0x9c, 0x4e, 0x22, 0xda, 0x35, 0x4e, 0xef, 0xe9, 0x68, 0xf1,
	0x12, 0xd1, 0xae, 0xe9, 0x37, 0xa1, 0x41, 0x59, 0x91, 0x1d, 0x7c, 0x17, 0x9a, 0x94, 0x7d, 0x94,
	0x6c, 0xa7, 0x86, 0x29, 0xd8, 0xe7, 0x8a, 0xf1, 0x2f, 0x74, 0x16, 0x4c, 0xdd, 0x1c, 0xe7, 0xe7,
	0x4d, 0xfd, 0x3d, 0x3b, 0x3c, 0xeb, 0x35, 0xfc, 0x07, 0x9d, 0xe7, 0xbb, 0xac, 0x13, 0x56, 0x5f,
	0xf6, 0x6e, 0x2d, 0xbf, 0x96, 0xda, 0xfa, 0xf6, 0xff, 0xbf, 0x02, 0x00, 0x00, 0xff, 0xff, 0xa9,
	0x2b, 0x11, 0x46, 0x11, 0x02, 0x00, 0x00,
}
